### ISSUE TITLE
How does Huxley handle stashes?

### ISSUE THREAD

**Issue by marcelosomers** [chenglou/node-huxley#78]
I'm experimenting with Huxley for the first time on an existing project. I kept running into an error where I'd have 3 or 4 stashes sitting around. Here's what I did to start up Huxley:

1. Created my `Huxleyfile.json` in my project root
2. Ran `hux --record` and clicked through my first few screens
3. Committed the two generated files: `Huxleyfile.json` and `Huxleyfolder/project.record.json
4. Ran `hux`

At that point I'd get an error:

````
The tests now halt. You might have unfinished tasks.

Possibly unhandled Error: Command failed: unable to refresh index

    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
````

I'd also randomly get my most recent stash applied to the working directory. The only way I was able to resolve this issue was to delete all my stashes. Then `hux` ran just fine.

Is this the expected behavior?

**Comment by chenglou** [comment]
[Here](https://github.com/chenglou/node-huxley/blob/842eaa351b8878d7d35676f76fdee04101ff05fa/source/defaultWorkflow/defaultWorkflow.js#L16-L23)'s what it does. I admit that it's a bit magical. But less than that, you wouldn't have the workflow in the first place (maybe I should just remove it...).

Does this help? http://stackoverflow.com/questions/14825965/git-stash-unable-to-refresh-how-to-pop-only-some-files

If it gets complicated, you can always manually check the diffs with `-w` before you make the change, then `-c` after: https://github.com/chenglou/node-huxley/wiki/Advanced-usage
